version: '3'
services:
  bot:
    image: salloum/who-said-innopolis-bot
    build:
      context: ./who-said-innopolis-bot
    env_file: .env.bot
    restart: always
    depends_on:
      - mongodb

  server:
    image: salloum/who-said-innopolis-server
    build:
      context: ./who-said-innopolis-server
    env_file: .env.server
    ports:
      - 5000:5000
    restart: always
  mongodb:
    image: mongo:latest
    logging:
      options:
        max-size: 1g
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
